Fix problem with reviews on future presentations
ryukzak/course-bot pull request #105
Opened 2023-12-07 16:48 UTC by Ivanio1

Closed #104

2023-12-07 16:50 UTC, Ivanio1 commented on src/course_bot/presentation.clj
It was fixed by cljfmt.exe

2023-12-17 14:51 UTC, ryukzak requested changes

2023-12-17 14:51 UTC, ryukzak commented on src/course_bot/presentation.clj
> +            (talk/send-text token id (tr :pres/too-early))
Do you mean" "You can't five a feedback to the future lesson"?

Also, we need a test for it.

2023-12-18 11:23 UTC, Ivanio1 commented
All fixed.

2023-12-23 00:51 UTC, merged

2023-12-23 00:52 UTC, ryukzak commented
Sorry, but I can't bring you more scores for the quests.