Improve error message on lab1 feed back
ryukzak/course-bot pull request #106
Opened 2023-12-09 12:50 UTC by Ivanio1

Close #45

2023-12-11 08:59 UTC, Ivanio1 commented
@ryukzak

2023-12-17 14:54 UTC, ryukzak requested changes

2023-12-17 14:54 UTC, ryukzak commented on test/course_bot/presentation_test.clj
> +                      "Lesson feedback is not available. Your lab1 group: lgr1. Now: 2022.01.01 11:29 +0000. Expected feedback dates:\n- 2022.01.01 12:30 +0000 -- 2022.01.01 15:00 +0000\n- 2022.01.02
Use `tt/unlines` instead of `\n`

2023-12-17 14:54 UTC, ryukzak commented on src/course_bot/presentation.clj
> +                                                                                                                                                                   (str/join "\n")))))))
Reduce line length and make it readable

2023-12-17 15:20 UTC, Ivanio1 commented
@ryukzak All fixed

2023-12-23 00:54 UTC, merged

2023-12-23 01:49 UTC, ryukzak commented
Small fix for your code: https://github.com/ryukzak/course-bot/commit/ac1b9a864974800df2675c9d083d1250819a1e4e