Improve Russian language texts
ryukzak/course-bot pull request #109
Opened 2023-12-14 19:21 UTC by Kimiega

fix #39 

Beliakov Dmitrii P33131

2023-12-14 19:29 UTC, Kimiega commented
@ryukzak

2024-01-05 13:00 UTC, ryukzak requested changes

2024-01-05 16:07 UTC, Kimiega commented on src/course_bot/presentation.clj
> +    :drop "сбросить"
Looks like it's used here https://github.com/ryukzak/course-bot/blob/5d6472889403a6ab54199ff990ccadd16ea5e7bc/src/course_bot/presentation.clj#L657

2024-01-10 10:59 UTC, ryukzak approved these changes

2024-01-10 10:59 UTC, merged

2024-01-10 11:00 UTC, ryukzak commented
Text me in telegram