fixed where presentation test failed
ryukzak/course-bot pull request #18
Opened 2023-01-20 15:07 UTC by AliIbadullayev

Changed way of rounding to fixed length a double

2023-01-20 17:08 UTC, ryukzak commented
Thank you! Can you extract this function to misc module and use in all such places?

2023-01-21 00:39 UTC, AliIbadullayev commented
* Rewrote test in modern way  according to #15
* Added 'to-fixed' func in misc module and replaced in all places where used  
* Removed unused functions and unused modules from headers 
* Added some other function to misc module: `quiz-answ`

2023-01-21 17:38 UTC, ryukzak commented
Sorry, but can you split it into several PRs by their purpose? Contact me by telegram.

2023-01-22 14:14 UTC, ryukzak requested changes
Also, can you squash all you commits in one.

2023-01-22 14:14 UTC, ryukzak commented on src/course_bot/misc.clj
> +(defn to-fixed [num len] (double (/ (Math/round (* (Math/pow 10 len) num)) (Math/pow 10 len))))
Please, rename it to round-2

2023-01-22 18:12 UTC, AliIbadullayev commented on src/course_bot/misc.clj
> +(defn to-fixed [num len] (double (/ (Math/round (* (Math/pow 10 len) num)) (Math/pow 10 len))))
done

2023-01-22 23:14 UTC, merged