Add configuration option to enable/disable essays
ryukzak/course-bot pull request #34
Opened 2023-09-07 20:22 UTC by Kaladin13

We should be able to configure this behavior from config without changing the source code every time

Lagus Maksim, P33081

2023-09-09 14:35 UTC, ryukzak commented
Fully agree with you, but we need to do it in a little bit different way:

1. We need to enable/disable essays by one.
2. Current way to make configuration is too complicated and magic. So it was reworked here: https://github.com/ryukzak/course-bot/pull/36 (will merge when I fix production config)
3. The simplest solution -- comment out essay from the config, if we don't need it right now.
4. Better solution -- do it like for quiz. Put all essays config in `{:essays {1 {...} 2 {...}}}`. Generate command for each mention essay.

2023-10-05 17:20 UTC, ryukzak requested changes
- conflict
- separate configuration for different essays

2023-10-10 10:00 UTC, Kaladin13 commented
@ryukzak 
I've added essays enabling based on their presence in new config, so when we add configuration for next essay, it will be  automatically added to the bot

2023-10-16 11:15 UTC, ryukzak commented on src/course_bot/csa.clj
> +         (essay/myfeedback-talk db conf "essay3")))
- When is much better.
- Do you actually check it? I don't sure hat `nil` value is available in `handlers/defhandler`?

2023-10-18 22:50 UTC, ryukzak commented
Implemented in https://github.com/ryukzak/course-bot/pull/52 (sorry, not clean)

Thank you for the attempt!

2023-10-18 22:50 UTC, closed without merging