Update external libraries versions
ryukzak/course-bot pull request #53
Opened 2023-10-19 16:35 UTC by Ivanio1

Closed #49

2023-10-19 16:36 UTC, Ivanio1 commented
@ryukzak

2023-10-24 09:37 UTC, Ivanio1 commented
@ryukzak waiting for merging and ready to open new MR - improving whoami command

2023-10-25 07:37 UTC, Ivanio1 commented
Closed #46

2023-10-25 07:37 UTC, Ivanio1 commented
@ryukzak

2023-10-25 11:07 UTC, ryukzak requested changes
1. Please, separate formatting changes from actual changes to different PRs.
2. Such reformatting I can approve only if it is a result of autoformatter works (so it should be checked by CI). So it should be for whole project or bot applied.

```clj
     :restart-wrong-input           "Неправильный ввод. Ожидается: /restart 12345"
     :restarted-and-notified        "Перезапущено и уведомлено: "
     :use-start-once-more           "Вы можете использовать /start еще раз."
```

3. Please, rewrite connected test in this way: https://github.com/ryukzak/course-bot/pull/55/files

2023-10-25 11:07 UTC, ryukzak commented on src/course_bot/general.clj
> +                (not allow-restart))
Old formatting is better.

2023-10-25 11:14 UTC, ryukzak requested changes

2023-10-25 11:14 UTC, ryukzak commented on src/course_bot/general.clj
> +         grouplab1                                    (-> lab1 :group)]
```suggestion
         grouplab1                                    (-> pres :lab1 :group)]
```

2023-10-25 11:14 UTC, ryukzak commented on src/course_bot/general.clj
> +         grouplab1                                    (-> lab1 :group)]
In theory, csa.clj can specify several presentations for the course. So we need to pass it as an argument to `whoami-talk` command. Like:

```clj
      (general/whoami-talk db conf (pres/group "lab1") (pres/group "labN"))
```

The output of `pres/group` should be connected to the end of normal whoami messages

2023-10-25 11:20 UTC, closed without merging

2023-10-25 11:20 UTC, Ivanio1 commented
@ryukzak Okay, I will close this PR, then open First PR about updating versions. And after merging I will continue to work with whoami.