fix(quiz): sort quizzes output correctly
ryukzak/course-bot pull request #74
Opened 2023-11-14 16:25 UTC by Moleus

fixes: #72 

Added quiz-10 to test that now sort works as expected. This implementation extracts a number from quiz name and sorts quizzes by the extracted value. If the name doesn't contain a number i.e `test-quiz`, 0 is mapped to it so the has the highest priority. 

Any suggestions or improvements are welcome :smiley:

2023-11-15 23:27 UTC, ryukzak requested changes
Looks good, but it is a limited solution. What happen if several numbers present in the string?

You can replace numbers in the keys by numbers with leading zeros. How many zeros? All numbers should have the same length. 

E.g. asd1qw1112a12 to asd0001qw1112a0012

2023-11-18 11:44 UTC, Moleus commented
Implemented sort with numbers replaced with leading zeros. The number of zeros is calculated based on the longest digits sequence in array of strings. 

What do you think about use of "Squash and Merge" GitHub feature while accepting PR to keep the master history clean? ;)

2023-11-26 13:21 UTC, ryukzak requested changes
Almost. Thank you

2023-11-26 13:21 UTC, ryukzak commented on src/course_bot/quiz.clj
> +                                    (sort-map-by-digits-in-key)
```suggestion
                                    sort-map-by-digits-in-key
```

2023-11-26 13:21 UTC, ryukzak commented on src/course_bot/quiz.clj
> +(defn prepend-leading-zeros [s, total-digits-count]
```suggestion
(defn prepend-leading-zeros [s total-digits-count]
```

2023-11-26 13:21 UTC, ryukzak commented on src/course_bot/quiz.clj
> +(defn get-longest-digits-seq [string] (apply max (conj (map count (re-seq #"\d+" string)) 0)))
```suggestion
(defn get-longest-digits-seq [string] (apply max 0 (map count (re-seq #"\d+" string))))
```

2023-11-26 13:21 UTC, ryukzak commented on src/course_bot/quiz.clj
> +(defn find-longest-digits-seq-in-array [array] (apply max (map get-longest-digits-seq array)))
list

2023-11-30 17:18 UTC, ryukzak approved these changes

2023-11-30 17:19 UTC, merged